name: chill_outz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  path_provider: ^2.1.5
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/videos/video1.mp4
    - assets/videos/video2.mp4
    - assets/videos/video3.mp4
    - assets/videos/video4.mp4
    - assets/videos/video5.mp4